### ISSUE TITLE
Double precision constants not set correctly

### ISSUE THREAD

**Issue by Beliavsky** [jeffreyguevaracorzo/NH-TOPOPT-FORTRAN#1]
In https://github.com/jeffreyguevaracorzo/NH-TOPOPT-FORTRAN/blob/main/Modules/Base_Module.f90

code such as

`double precision, parameter                             :: Pi = 3.14159265358979323846`

does not set double precision constants correctly, since literals by default are single precision, even if many digits are supplied. You could write

`double precision, parameter                             :: Pi = 3.14159265358979323846d0`

instead. For example, the program

```
implicit none
double precision, parameter :: Pi = 3.14159265358979323846
double precision, parameter :: dpi = 3.14159265358979323846d0
print*,pi
print*,dpi
end
```
gives output

```
   3.1415927410125732     
   3.1415926535897931 
```

**Comment by jeffreyguevaracorzo** [comment]
you're right, I hadn't noticed that, thanks for the comment.
